from: '/'
to: '/shell'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://docs.mongodb.com/getting-started'}
---
from: '/node'
to: '/quick-start'
type: redirect
code: 301
outputs:
   - {'getting-started': 'http://mongodb.github.io/node-mongodb-native/2.2'}
---
from: '/cpp'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/'}
---
from: '/cpp/introduction'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/'}
---
from: '/cpp/import-data'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/'}
---
from: '/cpp/client'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/'}
---
from: '/cpp/insert'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
---
from: '/cpp/query'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
---
from: '/cpp/update'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
---
from: '/cpp/remove'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
---
from: '/cpp/aggregation'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
---
from: '/cpp/indexes'
to: '/'
type: redirect
code: 301
outputs:
   - {'getting-started': 'https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial'}
...
