# If migrating as *.rst from another repo,
# Add to .gitignore
#
source: build/docs/source/administration/install-on-linux.txt
target: tutorial/install-on-linux.rst
---
source: build/docs/source/includes/toc-install-on-linux-landing.yaml
target: includes/toc-install-on-linux-landing.yaml
transform:
  regex: "file: /administration/install-on-linux"
  replace: "file: /tutorial/install-on-linux"
---
source: build/docs/source/tutorial/install-mongodb-on-red-hat.txt
target: tutorial/install-mongodb-on-red-hat.txt
---
source: build/docs/source/tutorial/install-mongodb-on-windows.txt
target: tutorial/install-mongodb-on-windows.rst
---
source: build/docs/source/includes/steps-create-manually-windows-service-for-mongodb.yaml
target: includes/steps-create-manually-windows-service-for-mongodb.yaml
---
source: build/docs/source/includes/steps-get-mongodb-for-windows.yaml
target: includes/steps-get-mongodb-for-windows.yaml
---
source: build/docs/source/includes/steps-install-mongodb-on-windows-unattended.yaml
target: includes/steps-install-mongodb-on-windows-unattended.yaml
---
source: build/docs/source/includes/fact-selinux-redhat-options.rst
target: includes/fact-selinux-redhat-options.rst
---
source: build/docs/source/includes/steps-run-mongodb-on-linux.yaml
target: includes/steps-run-mongodb-on-linux.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: build/docs/source/includes/steps-run-mongodb-on-a-linux-distribution.yaml
target: includes/steps-run-mongodb-on-a-linux-distribution.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: build/docs/source/includes/steps-run-mongodb-on-debian.yaml
target: includes/steps-run-mongodb-on-debian.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: build/docs/source/includes/steps-run-mongodb-on-windows.yaml
target: includes/steps-run-mongodb-on-windows.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
target: build/docs/source/includes/list-mongodb-org-packages.rst
source: includes/list-mongodb-org-packages.rst
...